Onmoim/Onmoim-Backend

- .github/workflows/deploy.yml
- 테스트 실패 원인(로컬 컨테이너 종료) 해결 후 배포 재시도
---
---
---
- [ x] Label을 지정했나요?
---
> chore: GitHub Actions 배포 재시도 로컬 컨테이너 종료로 인한 테스트 실패 문제 해결

- .github/workflows/deploy.yml
---
---
- 깃허브 액션 테스트용: 서브 모듈 yaml 복사 확인 
---
---
---
---
> chore: github actions test

- .github/workflows/deploy.yml
---
---
- deploy.yml 수정 빌드 테스트 프로필로 실행
---
---
---
---
---
> chore: deploy.yml 수정 빌드 테스트 프로필로 실행

- .github/workflows/deploy.yml
---
---
- deploy.yml 수정: github actions 테스트용 mysql/redis 실행 추가 
---
---
---
---
---
> chore: deploy.yml 수정 github actions 테스트용 redis mysql 실행 추가

- src/main/java/com/onmoim/server/example/controller/RedisController.java
---
---
- 배포 환경 레디스 테스트를 위해 레디스 테스트 컨트롤러 프로필 설정 삭제
---
---
---
---
---
> chore: config, redis 테스트 컨트롤러 프로필 설정 삭제

- .github/workflows/deploy.yml
> chore: deploy.yml 최신 반영

- src/test/resources/application-test.yml
- src/test/resources/application.yml
> chore: application-test.yml 수정

- .github/workflows/deploy.yml
> chore: application.yml 수정

- src/main/java/com/onmoim/server/health/controller/HealthCheckController.java
[Health] HealthCheckController 생성
---
---
/health GET 요청 시 서버 상태 확인용 응답을 반환하는 HealthCheckController 생성
---
---
---
---
---
> [Health] HealthCheckController 생성

- src/main/java/com/onmoim/server/config/SwaggerConfig.java
> feat: 배포 환경에 Swagger UI 적용

- build.gradle
- src/main/java/com/onmoim/server/common/exception/GlobalExceptionHandler.java
- src/main/java/com/onmoim/server/common/response/Message.java
- src/main/java/com/onmoim/server/common/response/ResponseHandler.java
---
---
- build.gradle: Querydsl 의존성 추가 
- GlobalExceptionHandler: 중복 코드 제거 (@ResponseStatus, ResponseEntity HttpStatus 통합)
- GlobalExceptionHandler: MethodArgumentNotValidException, Exception 예외 처리 추가 -
- ResponseHandler: 메시지 enum을 사용하여 응답 메시지 관리
- ResponseHandler: MethodArgumentNotValidException 처리 위한 FieldErrorResponse 추가
- ResponseHandler: 예외별 errorResponse 오버라이딩 (CustomException, MethodArgumentNotValidException, Exception)
---
- HttpStatus 상태 코드 @ReponseStatus ReponseEntity.status 중복 제거
- Exception 3가지로 구분 
- Exception: Server Error
- MethodArgumentNotValidException: Request Valid 
- CustomException
- 응답 메시지 내부 enum 관리
- errorResponse 오버라이딩
- FieldErrorResponse record 처리 
---
---
---
---
- 리뷰는 Reviewer로 지정된 …
> Chore: Querydsl 추가

- src/main/java/com/onmoim/server/common/exception/GlobalExceptionHandler.java
- src/main/java/com/onmoim/server/common/s3/controller/S3Controller.java
> fix: 체크 스타일 오류 수정

- src/main/java/com/onmoim/server/group/controller/GroupController.java
- src/main/java/com/onmoim/server/group/dto/request/CreateGroupRequestDto.java
- src/main/java/com/onmoim/server/group/entity/GroupUser.java
- src/main/java/com/onmoim/server/group/entity/Status.java
- src/main/java/com/onmoim/server/group/repository/GroupUserRepository.java
- src/main/java/com/onmoim/server/group/service/GroupService.java
- src/main/java/com/onmoim/server/group/service/GroupUserQueryService.java
- src/test/java/com/onmoim/server/group/service/GroupServiceTest.java
모임 좋아요(찜) 기능 추가
---
---
- GroupController, GroupService: 모임 좋아요 기능 추가
- GroupUser: 상태에 따라서 좋아요, 취소 기능 추가
- GroupUserQueryService: 상태에 따라 변경 감지 또는 저장 기능 추가
- GroupUserRepository: 주석 삭제 및 카운트 쿼리 메서드 네이밍 변경
- Status: PENDING 상태 설명 변경
- GroupServiceTest: 모임 좋아요, 취소 테스트 추가
---
```java
public void like() {
switch (status) {
case OWNER:
case MEMBER:
throw new CustomException(GROUP_ALREADY_JOINED);
case BAN:
throw new CustomException(GROUP_BANNED_MEMBER);
case BOOKMARK:
this.status = Status.PENDING;
break;
case PENDING:
this.status = Status.BOOKMARK;
}
}
```
현재 좋아요 기능은 크게 3가지로 동작합니다
OWNER, MEMBER, BAN -> 예외 처리
좋아요: PENDING(처음으로 GroupUser 관계가 생성된 경우 또는 좋아요 취소 이후) -> BOOKMARK
좋아요 취소: BOOKMARK -> PENDING
---
---
---
---
- …
> feat: 모임 좋아요(찜) 추가

- src/test/java/com/onmoim/server/location/service/LocationServiceTest.java
---
---
- repository 내 메서드 변경 후 테스트코드에 남아있던 기존 메서드명 수정
---
---
---
---
---
> fix: 테스트에 제거된 메서드명 변경

- src/main/java/com/onmoim/server/common/exception/ErrorCode.java
- src/main/java/com/onmoim/server/config/SecurityConfig.java
- src/main/java/com/onmoim/server/oauth/controller/AuthController.java
- src/main/java/com/onmoim/server/oauth/service/impl/OAuthServiceImpl.java
- src/main/java/com/onmoim/server/oauth/service/provider/KakaoOAuthProvider.java
- src/main/java/com/onmoim/server/oauth/service/provider/OAuthProviderFactory.java
- src/main/java/com/onmoim/server/security/JwtProvider.java
- src/main/java/com/onmoim/server/user/controller/UserController.java
- src/main/java/com/onmoim/server/user/dto/SignupRequest.java
- src/main/java/com/onmoim/server/user/service/impl/UserServiceImpl.java
- src/main/resources/static/test-google-login.html
- src/main/resources/static/test-kakao-login.html
---
---
- accessToken 발급 수정
- 카카오 로그인 구현
- dev.yml redis host 변경
- 회원가입 로직 UserController로 분리 및 User/Auth Controller api 주소 변경
- 예외 처리 CustomException으로 통일
---
> 로그인 테스트 방법 문서대로 로그인 테스트 진행 후 정상적으로 sns 로그인이 진행되는지 확인 부탁드립니다.
---
---
---
---
> feat: 카카오 로그인 구현, refactor: UserController 분리 및 예외 처리 변경

- src/main/java/com/onmoim/server/initializer/DataInitializer.java
- src/main/java/com/onmoim/server/security/CustomUserDetails.java
- src/test/java/com/onmoim/server/group/service/GroupQueryServiceTest.java
---
---
- 지역 데이터 초기화 로직 CommandLineRunner로 변경(Order 어노테이션 사용 위함)
---
---
---
---
---
> refactor: 지역 데이터 초기화 로직 CommandLineRunner로 변경

- src/main/java/com/onmoim/server/config/SecurityConfig.java
- src/main/java/com/onmoim/server/config/SwaggerConfig.java
---
---
- swagger authorize 버튼 설정 추가
- security config filterChain에 jwtAuthenticationFilter 추가
---
> swagger에 authorize 버튼이 정상적으로 생겼는지, 해당 버튼 내에 /auth/oauth에서 발급된 accessToken을 입력 후 토큰이 필요한 api들이 정상적으로 작동되는지 확인 부탁드립니다!
---
---
---
---
> fix: swagger + security config 수정

- src/main/java/com/onmoim/server/common/exception/ErrorCode.java
- src/main/java/com/onmoim/server/common/exception/GlobalExceptionHandler.java
- src/main/java/com/onmoim/server/group/controller/GroupController.java
- src/main/java/com/onmoim/server/group/dto/response/CursorPageResponseDto.java
- src/main/java/com/onmoim/server/group/dto/response/GroupMembersResponseDto.java
- src/main/java/com/onmoim/server/group/repository/GroupUserRepositoryCustom.java
- src/main/java/com/onmoim/server/group/repository/GroupUserRepositoryCustomImpl.java
- src/main/java/com/onmoim/server/group/service/GroupService.java
- src/main/java/com/onmoim/server/group/service/GroupUserQueryService.java
- src/test/java/com/onmoim/server/group/service/GroupServiceTest.java
---
---
- 모임 회원 커서 기반 조회 구현
- GlobalExceptionHandler 400 status 응답 고정 수정
---
---
---
---
---
> feat: 모임 회원 조회

- src/main/java/com/onmoim/server/config/SecurityConfig.java
- src/test/java/com/onmoim/server/TestSecurityConfig.java
- src/test/java/com/onmoim/server/common/s3/controller/S3ControllerTest.java
- src/test/java/com/onmoim/server/group/controller/GroupControllerTest.java
- src/test/java/com/onmoim/server/post/controller/GroupPostControllerTest.java
---
---
- SecurityConfig 테스트 환경과 나머지 환경 분리
- @WebMvcTest 관련 테스트 수정
---
노션에 @WebMvcTest + @ContextConfiguration 코드를 왜 수정했는지 이유를 정리해 봤습니다.
참고해서 리뷰해 주시면 감사하겠습니다!
---
---
https://parallel-shrine-c64.notion.site/WebMvcTest-1fc7d6692ca8800aa853c98ebf20bed5
---
---
>  fix: Security, 테스트 리팩토링

- build.gradle
- src/main/java/com/onmoim/server/common/exception/ErrorCode.java
- src/main/java/com/onmoim/server/config/SecurityConfig.java
- src/main/java/com/onmoim/server/location/repository/LocationRepository.java
- src/main/java/com/onmoim/server/oauth/constant/OAuthApiConstants.java
- src/main/java/com/onmoim/server/oauth/service/provider/GoogleOAuthProvider.java
- src/main/java/com/onmoim/server/oauth/service/provider/KakaoOAuthProvider.java
- src/main/java/com/onmoim/server/oauth/service/provider/OAuthProvider.java
- src/main/java/com/onmoim/server/oauth/service/provider/OAuthProviderFactory.java
- src/main/java/com/onmoim/server/user/controller/UserController.java
- src/main/java/com/onmoim/server/user/dto/request/CreateUserCategoryRequestDto.java
- src/main/java/com/onmoim/server/user/dto/request/SignupRequestDto.java
- src/main/java/com/onmoim/server/user/dto/response/ProfileResponseDto.java
- src/main/java/com/onmoim/server/user/entity/User.java
- src/main/java/com/onmoim/server/user/mapper/UserMapper.java
- src/main/java/com/onmoim/server/user/mapper/UserMapperCustom.java
- src/main/java/com/onmoim/server/user/mapper/UserMapperCustomImpl.java
- src/main/java/com/onmoim/server/user/repository/UserCategoryRepository.java
- src/main/java/com/onmoim/server/user/service/UserService.java
- src/main/java/com/onmoim/server/user/service/impl/UserServiceImpl.java
- src/test/java/com/onmoim/server/user/service/UserServiceTest.java
---
---
- 회원가입/관심사 선택 api 분리
- 프로필 조회
---
- mapstruct을 사용해 entity를 dto로 변환하도록 작업하였습니다. 확인 부탁드립니다.
---
- 밤에 테스트 코드 추가하겠습니다 T.T
---
---
---
> refactor: 회원가입과 관심사 선택 api 분리, feat: 프로필 조회

- src/test/java/com/onmoim/server/user/service/UserServiceTest.java
---
---
- 빌드 실패로 테스트 코드 수정
---
---
---
---
---
> fix: user 테스트 코드 수정

- src/main/java/com/onmoim/server/OnmoimApplication.java
import 누락 hotfix
---
---
---
---
---
---
---
> fix: enable-async import add

- src/main/java/com/onmoim/server/config/RedisConfig.java
- src/main/java/com/onmoim/server/config/SecurityConfig.java
- src/main/java/com/onmoim/server/oauth/service/impl/RefreshTokenServiceImpl.java
---
---
- RedisConfig 수정
---
---
---
---
---
> fix: RedisConfig 수정

- src/test/java/com/onmoim/server/user/service/UserServiceTest.java
> fix: 테스트 코드 수정

- src/main/java/com/onmoim/server/config/SecurityConfig.java
- src/main/java/com/onmoim/server/oauth/service/OAuthService.java
- src/main/java/com/onmoim/server/oauth/service/impl/OAuthServiceImpl.java
- src/main/java/com/onmoim/server/user/controller/UserController.java
- src/main/java/com/onmoim/server/user/dto/response/SignupResponseDto.java
- src/main/java/com/onmoim/server/user/service/UserService.java
- src/main/java/com/onmoim/server/user/service/impl/UserServiceImpl.java
- src/test/java/com/onmoim/server/user/service/UserServiceTest.java
---
---
- 가입 유저 로그인 시 카테고리 있는 경우, 없는 경우 return 분기
- 회원가입 시 jwt 리턴하도록 수정
---
---
---
---
---
> [User] 로그인 및 회원가입 수정

- src/main/java/com/onmoim/server/common/exception/ErrorCode.java
- src/main/java/com/onmoim/server/initializer/DataInitializer.java
- src/main/java/com/onmoim/server/user/dto/request/SignupRequestDto.java
- src/main/java/com/onmoim/server/user/dto/request/UpdateProfileRequestDto.java
- src/main/java/com/onmoim/server/user/dto/response/ProfileResponseDto.java
- src/main/java/com/onmoim/server/user/entity/User.java
- src/main/java/com/onmoim/server/user/mapper/UserMapperCustomImpl.java
- src/main/java/com/onmoim/server/user/service/impl/UserServiceImpl.java
- src/test/java/com/onmoim/server/user/service/UserServiceTest.java
---
---
- User 엔티티 내 Location 연간 관계 매핑
- 관련 테스트 코드 수정
---
---
---
---
---
> [User] User 엔티티 내 Location 연관 관계 매핑

- src/main/java/com/onmoim/server/common/exception/ErrorCode.java
- src/main/java/com/onmoim/server/common/s3/service/S3FileStorageService.java
- src/main/java/com/onmoim/server/group/implement/GroupQueryService.java
- src/main/java/com/onmoim/server/meeting/service/MeetingService.java
- src/test/java/com/onmoim/server/common/s3/service/S3FileStorageServiceTest.java
---
---
- 이미지 접근용 return url cloudfront 도메인으로 변경
- cloudfront url 기반 삭제 로직 수정
- 테스트 코드 수정
---
---
---
---
---
> [S3] 이미지 접근 url cloudfront로 변경

- src/main/java/com/onmoim/server/group/controller/GroupController.java
- src/main/java/com/onmoim/server/group/dto/ActiveGroupRelation.java
- src/main/java/com/onmoim/server/group/dto/PopularGroupRelation.java
- src/main/java/com/onmoim/server/group/dto/PopularGroupSummary.java
- src/main/java/com/onmoim/server/group/dto/response/GroupInfoResponseDto.java
- src/main/java/com/onmoim/server/group/implement/GroupQueryService.java
- src/main/java/com/onmoim/server/group/repository/GroupRepositoryCustom.java
- src/main/java/com/onmoim/server/group/repository/GroupRepositoryCustomImpl.java
- src/main/java/com/onmoim/server/group/service/GroupService.java
- src/main/java/com/onmoim/server/location/entity/Location.java
- src/test/java/com/onmoim/server/group/implement/GroupQueryServiceTest.java
---
---
- 내 주변 인기 모임 조회 테스트 추가
- 활동이 활발한 모임 조회 로직 수정 및 테스트 추가
---
---
---
---
---
> [모임] 인기 있는 모임 조회 2개 수정 및 테스트 

- src/main/java/com/onmoim/server/group/dto/GroupDetail.java
- src/main/java/com/onmoim/server/group/dto/response/GroupDetailResponseDto.java
- src/main/java/com/onmoim/server/group/dto/response/GroupInfoResponseDto.java
- src/main/java/com/onmoim/server/group/implement/GroupQueryService.java
- src/main/java/com/onmoim/server/group/repository/GroupRepositoryCustom.java
- src/main/java/com/onmoim/server/group/repository/GroupRepositoryCustomImpl.java
- src/main/java/com/onmoim/server/group/service/GroupService.java
- src/test/java/com/onmoim/server/group/implement/GroupQueryServiceTest.java
---
---
- 응답 dto 수정
- 모임 대표 이미지 추가
- 현재 사용자와 모임과의 관계 추가
- 모임 상세 조회 수정
- 모임 존재 조회, 모임 상세 조회, 현재 사용자와의 관계 조회 3개의 쿼리 -> 1개의 쿼리로 수정
- 모임 상세 조회 테스트 추가
---
---
---
---
---
> refactor: [모임] 상세 조회 수정

- src/main/java/com/onmoim/server/common/exception/ErrorCode.java
- src/main/java/com/onmoim/server/group/dto/request/GroupCreateRequestDto.java
- src/main/java/com/onmoim/server/group/dto/request/GroupUpdateRequestDto.java
- src/main/java/com/onmoim/server/group/dto/response/GroupDetailResponseDto.java
- src/main/java/com/onmoim/server/group/entity/Group.java
---
---
- 응답 필드 누락 이슈 해결
---
---
---
---
---
> fix: [모임] 상세 조회 수정

- src/main/java/com/onmoim/server/common/response/CommonCursorPageResponseDto.java
- src/main/java/com/onmoim/server/group/controller/GroupController.java
- src/main/java/com/onmoim/server/group/dto/response/GroupSummaryResponseDto.java
- src/main/java/com/onmoim/server/group/dto/response/JoinedGroupResponseDto.java
- src/main/java/com/onmoim/server/group/dto/response/RecentViewedGroupSummaryResponseDto.java
- src/main/java/com/onmoim/server/group/dto/response/cursor/RecentViewCursorPageResponseDto.java
- src/main/java/com/onmoim/server/group/entity/GroupViewLog.java
- src/main/java/com/onmoim/server/group/implement/GroupLikeQueryService.java
- src/main/java/com/onmoim/server/group/implement/GroupQueryService.java
- src/main/java/com/onmoim/server/group/implement/GroupUserQueryService.java
- src/main/java/com/onmoim/server/group/repository/GroupLikeRepository.java
- src/main/java/com/onmoim/server/group/repository/GroupLikeRepositoryCustom.java
- src/main/java/com/onmoim/server/group/repository/GroupLikeRepositoryCustomImpl.java
- src/main/java/com/onmoim/server/group/repository/GroupRepositoryCustom.java
- src/main/java/com/onmoim/server/group/repository/GroupRepositoryCustomImpl.java
- src/main/java/com/onmoim/server/group/repository/GroupUserRepository.java
- src/main/java/com/onmoim/server/group/repository/GroupUserRepositoryCustom.java
- src/main/java/com/onmoim/server/group/repository/GroupUserRepositoryCustomImpl.java
- src/main/java/com/onmoim/server/group/repository/GroupViewLogRepository.java
- src/main/java/com/onmoim/server/group/repository/GroupViewLogRepositoryCustom.java
- src/main/java/com/onmoim/server/group/repository/GroupViewLogRepositoryCustomImpl.java
- src/main/java/com/onmoim/server/group/service/GroupService.java
- src/main/java/com/onmoim/server/user/controller/UserController.java
- src/test/java/com/onmoim/server/group/implement/GroupLikeQueryServiceTest.java
- src/test/java/com/onmoim/server/group/implement/GroupQueryServiceTest.java
- src/test/java/com/onmoim/server/group/implement/GroupUserQueryServiceTest.java
- src/test/java/com/onmoim/server/group/service/GroupServiceTest.java
---
---
- 가입한 모임 조회
- 찜한 모임 조회
- 나와 비슷한 관심사 모임 조회
- 나와 가까운 모임 조회
- 모임 조회 로그 쌓기
- 최근 본 모임 조회
---
---
---
---
---
> [Group] 가입한/찜한/나와 비슷한 관심사/나와 가까운/최근 본 모임 조회

- src/main/java/com/onmoim/server/group/controller/GroupController.java
- src/main/java/com/onmoim/server/group/dto/response/GroupSummaryByCategoryResponseDto.java
- src/main/java/com/onmoim/server/group/implement/GroupQueryService.java
- src/main/java/com/onmoim/server/group/repository/GroupRepositoryCustom.java
- src/main/java/com/onmoim/server/group/repository/GroupRepositoryCustomImpl.java
- src/main/java/com/onmoim/server/group/service/GroupService.java
- src/test/java/com/onmoim/server/group/implement/GroupQueryServiceTest.java
---
---
- 카테고리별 모임 조회
---
---
---
---
---
> [Category] 카테고리별 모임 조회

- src/main/java/com/onmoim/server/category/controller/CategoryController.java
- src/main/java/com/onmoim/server/group/controller/GroupController.java
> [Category] refactor: 카테고리별 모임 조회 uri 및 컨트롤러 변경

- src/main/java/com/onmoim/server/group/repository/GroupLikeRepository.java
- src/main/java/com/onmoim/server/group/repository/GroupLikeRepositoryCustom.java
- src/main/java/com/onmoim/server/group/repository/GroupLikeRepositoryCustomImpl.java
- src/main/java/com/onmoim/server/group/repository/GroupUserRepositoryCustom.java
- src/main/java/com/onmoim/server/group/repository/GroupUserRepositoryCustomImpl.java
- src/main/java/com/onmoim/server/group/repository/GroupViewLogRepositoryCustom.java
- src/main/java/com/onmoim/server/group/repository/GroupViewLogRepositoryCustomImpl.java
- src/main/java/com/onmoim/server/user/dto/response/ProfileResponseDto.java
- src/main/java/com/onmoim/server/user/dto/response/UserCategoryResponseDto.java
- src/main/java/com/onmoim/server/user/entity/User.java
- src/main/java/com/onmoim/server/user/mapper/UserMapperCustomImpl.java
- src/main/java/com/onmoim/server/user/repository/UserCategoryRepository.java
---
---
- 프로필 조회 시 필드(성별, 카테고리 id, 최근 본/찜/가입한 모임 개수) 추가
---
---
---
---
---
> [User] 프로필 조회 필드 추가

- src/main/java/com/onmoim/server/meeting/controller/MeetingController.java
- src/main/java/com/onmoim/server/meeting/dto/request/UpcomingMeetingsRequestDto.java
- src/main/java/com/onmoim/server/meeting/dto/response/MeetingSummaryResponseDto.java
- src/main/java/com/onmoim/server/meeting/dto/response/UpcomingMeetingCursorPageResponseDto.java
- src/main/java/com/onmoim/server/meeting/repository/MeetingRepositoryCustom.java
- src/main/java/com/onmoim/server/meeting/repository/MeetingRepositoryCustomImpl.java
- src/main/java/com/onmoim/server/meeting/service/MeetingQueryService.java
- src/main/java/com/onmoim/server/meeting/service/MeetingService.java
- src/test/java/com/onmoim/server/meeting/service/MeetingQueryServiceTest.java
---
---
- 내모임 - 다가오는 일정 조회
---
---
---
---
---
> [Meeting] 다가오는 일정 조회

- src/test/java/com/onmoim/server/meeting/service/MeetingQueryServiceTest.java
> test: 테스트 baseTime 수정

- src/main/java/com/onmoim/server/meeting/repository/MeetingRepositoryCustomImpl.java
> fix: 다가오는 일정 조회 쿼리 수정

- src/main/java/com/onmoim/server/chat/common/config/WebSocketConfig.java
- src/main/java/com/onmoim/server/chat/common/config/WebSocketEventListener.java
- src/main/java/com/onmoim/server/chat/common/example/SocketTestController.java
- src/main/java/com/onmoim/server/chat/controller/rest/ChatMessageController.java
- src/main/java/com/onmoim/server/chat/domain/dto/ChatMessageDto.java
- src/main/java/com/onmoim/server/chat/domain/dto/SystemMessageDto.java
- src/main/java/com/onmoim/server/chat/domain/enums/SubscribeRegistry.java
- src/main/java/com/onmoim/server/chat/service/ChatMessageSendService.java
- src/main/java/com/onmoim/server/chat/service/ChatMessageService.java
- src/main/java/com/onmoim/server/chat/service/facade/ChatMessageFacade.java
- src/main/java/com/onmoim/server/chat/service/retry/ChatMessageRetryService.java
- src/main/java/com/onmoim/server/config/SecurityConfig.java
- src/main/java/com/onmoim/server/group/controller/GroupController.java
- src/main/java/com/onmoim/server/group/service/GroupService.java
> hot-fix: websocket security off

- src/test/java/com/onmoim/server/group/controller/GroupControllerTest.java
> Hot-fix: 모임 가입 테스트 반환값 수정

- src/main/java/com/onmoim/server/chat/common/config/WebSocketConfig.java
- src/main/java/com/onmoim/server/chat/controller/rest/ChatMessageController.java
- src/main/java/com/onmoim/server/chat/domain/ChatRoomMessageId.java
- src/main/java/com/onmoim/server/chat/domain/dto/ChatMessageDto.java
- src/main/java/com/onmoim/server/chat/domain/dto/ChatRoomListUpdateDto.java
- src/main/java/com/onmoim/server/chat/domain/dto/ChatRoomSummeryDto.java
- src/main/java/com/onmoim/server/chat/domain/dto/ChatUserDto.java
- src/main/java/com/onmoim/server/chat/domain/enums/SubscribeRegistry.java
- src/main/java/com/onmoim/server/chat/repository/ChatMessageRepository.java
- src/main/java/com/onmoim/server/chat/repository/ChatRoomListRepository.java
- src/main/java/com/onmoim/server/chat/repository/ChatRoomRepository.java
- src/main/java/com/onmoim/server/chat/repository/ChatRoomRepositoryCustom.java
- src/main/java/com/onmoim/server/chat/repository/ChatRoomRepositoryCustomImpl.java
- src/main/java/com/onmoim/server/chat/service/ChatMessageSendService.java
- src/main/java/com/onmoim/server/chat/service/ChatMessageService.java
- src/main/java/com/onmoim/server/chat/service/ChatRoomListService.java
- src/test/java/com/onmoim/server/chat/service/ChatMessageServiceTest.java
> fix: 이전 채팅 조회 Response 유저정보 추가
